### 종목 일봉 차트 단건 조회
GET http://localhost:8081/charts/2/latest
Content-Type: application/json

### 종목정보 단건 조회
GET http://localhost:8081/stocks/2
Content-Type: application/json

### 패턴탐지 단건 조회
GET http://localhost:8081/charts/2/patterns/33
Content-Type: application/json


### 종목 랭킹 리스트 조회
GET http://localhost:8081/stocks/rankings?category=RISE&date=2024-01-16
Content-Type: application/json


### 종목 랭킹 리스트 조회2
GET http://localhost:8081/stocks/rankings?category=RISE&date=2025-09-10
Content-Type: application/json


### 종목 일봉 차트 조회
GET http://localhost:8081/charts/2
Content-Type: application/json

### 종목 일봉 차트 조회(커서)
GET http://localhost:8081/charts/2?limit=100&cursorDate=2025-03-14
Content-Type: application/json


### 패턴 탐지 다건 조회
GET http://localhost:8081/charts/1/patterns?startDate=2025-08-01&endDate=2025-08-10
Content-Type: application/json


### 업종 다건 조회
GET http://localhost:8081/sectors
Content-Type: application/json


### 패턴 다건 조회
GET http://localhost:8081/patterns
Content-Type: application/json


### 패턴 다건 조회(상승형)
GET http://localhost:8081/patterns?direction=BEARISH
Content-Type: application/json


### 패턴 다건 조회(하락형)
GET http://localhost:8081/patterns?direction=BULLISH
Content-Type: application/json


### 패턴 탐지된 종목 다건 조회
GET http://localhost:8081/patterns/46
Content-Type: application/json


### 지표 이름 다건조회
GET http://localhost:8081/indicators
Content-Type: application/json


### 지표에 따른 지표 설정 다건조회
GET http://localhost:8081/indicators/1/configs
Content-Type: application/json


### 지표에 따른 지표 라인 다건조회
GET http://localhost:8081/indicators/1/lines
Content-Type: application/json


### 필터링된 종목 다건조회
POST http://localhost:8081/search?date=2025-08-04
Content-Type: application/json

{
  "sectorIds" : [ 1, 10 ],
  "chartFilterList" : [
    {
      "priceType" : "CHART_OPEN",
      "priceMin" : null,
      "priceMax" : 100000
    },
    {
      "priceType" : "CHART_VOLUME",
      "priceMin" : null,
      "priceMax" : 100000
    }
  ],
  "indicatorFilterList" : [
    {
      "indicatorId" : 1,
      "indicatorLineFilterList" : [
        {
          "filterType" : "COMPARE_INDICATOR",
          "indicatorLineIdA" : 1,
          "indicatorLineIdB" : 2,
          "operator" : "LESS_THAN_OR_EQUAL",
          "threshold" : null
        },
        {
          "filterType" : "COMPARE_INDICATOR",
          "indicatorLineIdA" : 1,
          "indicatorLineIdB" : 3,
          "operator" : "LESS_THAN_OR_EQUAL",
          "threshold" : null
        }
      ]
    },
    {
      "indicatorId" : 34,
      "indicatorLineFilterList" : [
        {
          "filterType" : "DIFFERENCE",
          "indicatorLineIdA" : 70,
          "indicatorLineIdB" : 71,
          "operator" : "GREATER_THAN",
          "threshold" : 0
        }
      ]
    }
  ]
}