### 종목 일봉 차트 단건 조회
GET http://localhost:8081/charts/4/latest
Content-Type: application/json

### 종목정보 단건 조회
GET http://localhost:8081/stocks/2
Content-Type: application/json

### 패턴탐지 단건 조회
GET http://localhost:8081/charts/2/pattern/39
Content-Type: application/json


### 종목 랭킹 리스트 조회
GET http://localhost:8081/stocks/rankings?category=VOLUME&date=2024-01-01
Content-Type: application/json


### 종목 랭킹 리스트 조회
GET http://localhost:8081/stocks/rankings?category=RISE&date=2025-07-17
Content-Type: application/json